export const message = {
    demoInfo: 'Demo使用说明',
    uploadOrUseDefault: '上传JSON格式文件（或直接使用样例文本）',
    jsonFormat: 'JSON文件格式如下：',
    dataDisplay: '数据显示',
    leftPage: '左侧会显示出标注页面',
    rightPage: '右侧会显示出对应JSON数据',
    annotate: '标注',
    selectText: '选择一些文字来标注',
    connection: '连接',
    clickToConnect: '点击两个标注来连接它们',
    delete: '删除',
    rightToDelete: '在标注或连接的文字部分右键可以删除对应元素',
    download: '下载JSON数据',
    clickToDownload: '点击下载即可',
    npmInfo: 'npm包使用说明',
    inYourWebProj: '在你的Web项目中：',
    andItIsInstalled: '即可安装。',
    readRef: '阅读下面的API Reference来了解具体使用方法',
    useExample: '使用样例文本',
    upload: '上传',
    downloadButton: '下载',
    switchLanguage: 'English'
};